pub mod player_input_controller;
pub mod projectile_controller;
pub mod destroy_on_event;
pub mod take_damage_on_hostile_collision;
pub mod destroy_on_hostile_collision;
pub mod fade_away;
pub mod spawn_giblets_on_death;
pub mod fade_in_and_out;
pub mod ai;